In [1]:
from lib.config import Config_f
from lib.data_set import Features
from lib.model import SimpleModel
from lib import utils

In [2]:
import ctypes
import pandas as pd
import numpy as np
import pywt
import matplotlib.pyplot as plt
import time

from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest,f_classif,chi2,mutual_info_classif,VarianceThreshold,RFE,SelectFromModel
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA

from sklearn.svm import SVC

## File name read

In [3]:
# read file name of data with various Labels
df = pd.read_csv('./useful_data_label.csv',index_col=0) 
# read file name of data with only label 0
df2 = pd.read_csv('./unuseful_data_label.csv',index_col=0)
# read some of the data with only label 0
df3 = pd.read_csv('./data/file_name.txt',header=None)
player = ctypes.windll.kernel32

ind = df2.iloc[1].isna()
files = np.concatenate([np.array(df.columns),np.array('normal/'+df2.columns[ind])])

## Configuration

In [4]:
# Override the base class of Config and Features for SVM Model
class SVM_Config(Config_f):
    NAME = 'SVM'
    NUM_CLASSES = 2

    CLASS_WEIGHTS = None
    FN_LP = 300
    DETREND_LAMBDA = 50
    TEST_FILES = files[[5,30,31,32,33,34,35]]
    
    # SVM parameters
    KERNEL = "rbf"
    GAMMA = "auto"
    C = 10
    CLASS_WEIGHTS = None
    
class SVM_dataset(Features):
    
    def __init__(self,config):
        super(SVM_dataset,self).__init__(config)
        self.config = config
        

In [5]:
# Generate SVM configuration
config = SVM_Config()
config.display()


Configurations:
BINS                           3
C                              10
CHANNELS                       ['LEFT_TA', 'LEFT_TS', 'LEFT_BF', 'LEFT_RF', 'RIGHT_TA', 'RIGHT_TS', 'RIGHT_BF', 'RIGHT_RF']
CLASS_WEIGHTS                  None
DETREND_LAMBDA                 50
FEATURES_LIST                  ['IEMG', 'SSI', 'WL', 'ZC', 'ku', 'SSC', 'skew', 'Acti', 'AR', 'HIST', 'MDF', 'MNF', 'mDWT']
FN_LP                          300
GAMMA                          auto
KERNEL                         rbf
LEVEL_DWT                      3
NAME                           SVM
NUM_CLASSES                    2
NUM_MF                         3
N_ENV                          20
RANGES                         (-3, 3)
RECT                           False
SAME_LABEL                     True
SCALE                          True
SHUFFLE                        True
STEP_SIZE                      512
TEST_FILES                     ['G07_Freezing_Trial1_trial_1_emg.csv'
 'normal/G09_Walking_trial_2_emg.cs

## Data generate

In [6]:
data = SVM_dataset(config)

In [7]:
# Choose features to use
data.feature_list = ['IEMG', 'SSI', 'WL', 'ZC', 'ku', 'SSC', 'skew', 'Acti', 'AR', 'HIST', 'MF','MDF', 'MNF', 'mDWT']
data.num_mf = 10

# Load data from files
data.load_data(files)

# Extract features from data
data.extract_features()

X_train,Y_train,_ = data.train_set
X_valid,Y_valid,_ = data.valid_set
X_test, Y_test, _ = data.test_set

skip
skip
3/174: G06_FoG_trial_1_emg.csv
4/174: G06_FoG_trial_2_emg.csv
5/174: G06_FoG_trial_3_emg.csv
6/174: G07_Freezing_Trial1_trial_1_emg.csv
7/174: G08_FoG_1_trial_1_emg.csv
8/174: G08_FoG_2_trial_1_emg.csv
9/174: G11_FoG_trial_1_emg.csv
10/174: G11_FoG_trial_2_emg.csv
11/174: P379_M050_2_OFF_A_FoG_trial_1_emg.csv
12/174: P379_M050_2_OFF_A_FoG_trial_2_emg.csv
13/174: P379_M050_2_OFF_A_FoG_trial_3_emg.csv
14/174: P379_M050_2_OFF_B_FoG_trial_1_emg.csv
15/174: P379_M050_2_OFF_B_FoG_trial_2_emg.csv
16/174: P379_M050_2_OFF_B_FoG_trial_3_emg.csv
17/174: P551_M050_2_A_FoG_trial_1_emg.csv
18/174: P551_M050_2_B_FoG_trial_1_emg.csv
19/174: P551_M050_2_B_FoG_trial_2_emg.csv
20/174: P812_M050_2_B_FoG_trial_1_emg.csv
21/174: P812_M050_2_B_FoG_trial_2_emg.csv
22/174: normal/G02_Walking_trial_1_emg.csv
23/174: normal/G03_Walking_trial_1_emg.csv
24/174: normal/G03_Walking_trial_2_emg.csv
25/174: normal/G05_Walking_struct_fixed_trial_1_emg.csv
26/174: normal/G05_Walking_struct_fixed_trial_2_emg.cs

171/174: normal/P940_MSham_A_Walking_trial_6_emg.csv
172/174: normal/P940_MSham_B_Walking_trial_2_emg.csv
173/174: normal/P940_MSham_B_Walking_trial_4_emg.csv
174/174: normal/P940_MSham_B_Walking_trial_6_emg.csv
threshold_WAMP:1.0, threshold_ZC:0.0, threshold_SSC:0.0, bins:3, ranges:(-3,3), num_mf:10, wavelet: db7, level: 3
['IEMG', 'SSI', 'WL', 'ZC', 'ku', 'SSC', 'skew', 'Acti', 'AR', 'HIST', 'MF', 'MDF', 'MNF', 'mDWT']
threshold_WAMP:1.0, threshold_ZC:0.0, threshold_SSC:0.0, bins:3, ranges:(-3,3), num_mf:10, wavelet: db7, level: 3
['IEMG', 'SSI', 'WL', 'ZC', 'ku', 'SSC', 'skew', 'Acti', 'AR', 'HIST', 'MF', 'MDF', 'MNF', 'mDWT']
threshold_WAMP:1.0, threshold_ZC:0.0, threshold_SSC:0.0, bins:3, ranges:(-3,3), num_mf:10, wavelet: db7, level: 3
['IEMG', 'SSI', 'WL', 'ZC', 'ku', 'SSC', 'skew', 'Acti', 'AR', 'HIST', 'MF', 'MDF', 'MNF', 'mDWT']


## Model

In [23]:
# Override base class of SimpleMode for SVM
class SVM_Model(SimpleModel):
    
    def build(self,config):
        
        model = SVC(kernel=config.KERNEL,
                    C=config.C,
                    class_weight=config.CLASS_WEIGHTS,
                    gamma=config.GAMMA)
        
        if config.CLASS_WEIGHTS != None:
            print('Using class weights:',config.CLASS_WEIGHTS)
        
        return model
        
    def predict(self, data):
        
        data = np.array(data)
        scaler = MinMaxScaler()
#         scaler.fit(np.concatenate([self.X_train,data]))
        X = scaler.fit_transform(data)
        if self.transformer != None:
            X = self.transformer.transform(X)
        results = self.simple_model.predict(X)

        return results

## Data split

In [24]:
# data split and processing for model
class_id = [2,6]
binary = True
x_train,y_train,x_valid,y_valid,x_test,y_test = utils.data_split((X_train,X_valid,X_test),
                                                                 (Y_train,Y_valid,Y_test),
                                                                 class_id,
                                                                 binary,
                                                                 random_state = 555)

## Model training

In [25]:
config.C = 10

if binary:
    config.CLASS_WEIGHTS = {0:1,1:5}
    config.NUM_CLASSES = 2
else:
    config.CLASS_WEIGHTS = None
    config.NUM_CLASSES = len(class_id)

# Generate SVM Model
svm_model = SVM_Model('SVM',config,'./model/SVM/')

Using class weights: {0: 1, 1: 5}


In [26]:
pca = PCA(n_components=150,copy=True)
sfm = SelectFromModel(GradientBoostingClassifier(),max_features=80)
rfe = RFE(estimator=LogisticRegression(max_iter=10000), n_features_to_select=100)
vt = VarianceThreshold(threshold=0.01)

svm_model.train((x_train,y_train),vt)

## Model evaluation

In [27]:
acc_train,cm_train = svm_model.model_metrics(x_train,y_train)
acc_valid,cm_valid = svm_model.model_metrics(x_valid,y_valid)
acc_test,cm_test = svm_model.model_metrics(x_test,y_test)
print('acc_train: %f\nconfusion_matrix:\n'%acc_train,cm_train,'\n')
print('acc_valid: %f\nconfusion_matrix:\n'%acc_valid,cm_valid,'\n')
print('acc_test: %f\nconfusion_matrix:\n'%acc_test,cm_test)

acc_train: 0.971762
confusion_matrix:
 [[5429  142]
 [  32  559]] 

acc_valid: 0.936740
confusion_matrix:
 [[1721  125]
 [   5  204]] 

acc_test: 0.936768
confusion_matrix:
 [[288  23]
 [  4 112]]
